import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useWorkflow } from '../../context/WorkflowContext';
import { Card, Button, Badge, AgentBadge } from '../../components/ui';
import {
  FileText,
  Copy,
  Download,
  RefreshCw,
  ArrowRight,
  Briefcase,
  CheckCircle2,
  AlertCircle,
  Save,
  Sparkles,
  ShieldCheck
} from 'lucide-react';

export const CoverLetterPage: React.FC = () => {
  const navigate = useNavigate();
  const {
    profile,
    selectedJob,
    tailoredResume,
    activeResumeVersion,
    coverLetter,
    generateCoverLetterForSelectedJob,
    updateCoverLetterContent,
    isLoading
  } = useWorkflow();

  const [copied, setCopied] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);
  const [clError, setClError] = useState<string | null>(null);
  const [editableContent, setEditableContent] = useState<string>('');

  useEffect(() => {
    if (coverLetter?.content) {
      setEditableContent(coverLetter.content);
    }
  }, [coverLetter?.content]);

  // --------------------------------------------------------------------------
  // PREREQUISITE CHECK 1: NO JOB SELECTED
  // --------------------------------------------------------------------------
  if (!selectedJob) {
    return (
      <div className="space-y-6 text-white font-sans">
        <div className="flex items-center gap-2">
          <h1 className="text-2xl font-bold text-white">Cover Letter Generation</h1>
          <AgentBadge code="AG-005" name="Cover Letter" />
        </div>
        <Card className="p-8 text-center space-y-4 bg-[#141414] border-white/10 max-w-xl mx-auto my-12">
          <div className="w-12 h-12 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 flex items-center justify-center mx-auto">
            <Briefcase className="w-6 h-6" />
          </div>
          <div className="space-y-1">
            <h3 className="text-lg font-semibold text-white">Select a target job before generating a cover letter.</h3>
            <p className="text-xs text-neutral-400">
              AG-005 requires a real target Job Description and Company context to produce a job-specific cover letter.
            </p>
          </div>
          <Button
            variant="whitePill"
            onClick={() => navigate('/app/jobs')}
            rightIcon={<ArrowRight className="w-4 h-4 text-black" />}
          >
            Browse Real Jobs (AG-002)
          </Button>
        </Card>
      </div>
    );
  }

  // --------------------------------------------------------------------------
  // PREREQUISITE CHECK 2: NO RESUME VERSION AVAILABLE
  // --------------------------------------------------------------------------
  const resumeVersionToUse = tailoredResume || activeResumeVersion;
  if (!resumeVersionToUse) {
    return (
      <div className="space-y-6 text-white font-sans">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <h1 className="text-2xl font-bold text-white">Cover Letter Generation</h1>
            <AgentBadge code="AG-005" name="Cover Letter" />
          </div>
        </div>

        {/* Selected Job Context */}
        <Card className="p-4 bg-[#111111] border-white/10 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <span className="text-xs font-semibold text-neutral-400 uppercase tracking-wider block">Selected Target Job</span>
            <div className="text-base font-bold text-white mt-0.5">{selectedJob.title}</div>
            <div className="text-xs text-neutral-300">{selectedJob.company} • {selectedJob.location}</div>
          </div>
        </Card>

        <Card className="p-8 text-center space-y-4 bg-[#141414] border-amber-800/40 max-w-xl mx-auto my-8">
          <div className="w-12 h-12 rounded-full bg-amber-500/10 border border-amber-500/20 text-amber-400 flex items-center justify-center mx-auto">
            <FileText className="w-6 h-6" />
          </div>
          <div className="space-y-1">
            <h3 className="text-lg font-semibold text-white">Optimize your resume before generating a cover letter.</h3>
            <p className="text-xs text-neutral-400 leading-relaxed">
              AG-005 consumes the exact DATA-004 tailored resume version generated by AG-004 to ensure 100% alignment between your resume claims and cover letter.
            </p>
          </div>
          <Button
            variant="whitePill"
            onClick={() => navigate('/app/resume/optimize')}
            rightIcon={<ArrowRight className="w-4 h-4 text-black" />}
          >
            Optimize Resume (AG-004)
          </Button>
        </Card>
      </div>
    );
  }

  // --------------------------------------------------------------------------
  // HANDLERS
  // --------------------------------------------------------------------------
  const handleGenerate = async () => {
    setClError(null);
    try {
      await generateCoverLetterForSelectedJob();
    } catch (err: any) {
      setClError(err.message || 'Failed to generate cover letter.');
    }
  };

  const handleSaveEdits = async () => {
    if (!editableContent.trim()) return;
    setClError(null);
    try {
      await updateCoverLetterContent(editableContent);
      setSaveSuccess(true);
      setTimeout(() => setSaveSuccess(false), 2000);
    } catch (err: any) {
      setClError(err.message || 'Failed to save cover letter edits.');
    }
  };

  const handleCopy = () => {
    const textToCopy = editableContent || coverLetter?.content || '';
    if (!textToCopy) return;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const textToDownload = editableContent || coverLetter?.content || '';
    if (!textToDownload) return;

    const blob = new Blob([textToDownload], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Cover_Letter_${selectedJob.company.replace(/[^a-zA-Z0-9]/g, '_')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8 text-white font-sans">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-2xl font-bold text-white">Job-Specific Cover Letter</h1>
            <AgentBadge code="AG-005" name="Cover Letter" />
          </div>
          <p className="text-xs text-neutral-400 mt-1">
            AG-005 produces a tailored cover letter referencing your DATA-004 resume qualifications for {selectedJob.company}.
          </p>
        </div>

        <div className="flex items-center gap-3">
          {coverLetter && (
            <>
              <Button variant="outline" size="sm" onClick={handleCopy} leftIcon={<Copy className="w-4 h-4" />}>
                {copied ? 'Copied!' : 'Copy Text'}
              </Button>
              <Button variant="outline" size="sm" onClick={handleDownload} leftIcon={<Download className="w-4 h-4" />}>
                Download Text / PDF
              </Button>
            </>
          )}
        </div>
      </div>

      {/* Target Job Context Banner */}
      <Card className="p-5 bg-[#111111] border-white/12 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold text-neutral-400 uppercase tracking-wider">Target Application Context</span>
            <Badge variant="brand" size="sm">AG-002</Badge>
          </div>
          <div className="text-base font-bold text-white">{selectedJob.title}</div>
          <div className="text-xs text-neutral-300">{selectedJob.company} • {selectedJob.location}</div>
        </div>

        <div className="sm:text-right space-y-1">
          <div className="flex items-center sm:justify-end gap-2">
            <span className="text-xs text-neutral-400">Linked Resume Version</span>
            <Badge variant="dark" size="sm">DATA-004</Badge>
          </div>
          <div className="text-xs text-emerald-400 font-mono font-medium">{resumeVersionToUse.id}</div>
        </div>
      </Card>

      {/* MANDATORY ANTI-FABRICATION GUARDRAIL BANNER */}
      <Card className="p-4 bg-[#111111] border-emerald-800/50 flex items-start gap-3">
        <ShieldCheck className="w-6 h-6 text-emerald-400 shrink-0 mt-0.5" />
        <div className="text-xs space-y-0.5">
          <span className="font-bold text-emerald-300 block">Ground-Truth Cover Letter Enforced:</span>
          <span className="text-neutral-300 leading-relaxed">
            AG-005 references only verified qualifications present in your profile and DATA-004 tailored resume. Zero unsupported claims, fake roles, or unverified achievements are added.
          </span>
        </div>
      </Card>

      {clError && (
        <Card className="p-4 bg-red-950/40 border-red-800/50 text-red-300 text-xs flex items-center gap-2">
          <AlertCircle className="w-4 h-4 text-red-400 shrink-0" />
          <span>{clError}</span>
        </Card>
      )}

      {/* TRIGGER GENERATION CARD IF NOT YET GENERATED */}
      {!coverLetter && (
        <Card className="p-8 text-center space-y-4 bg-[#141414] border-white/10 max-w-2xl mx-auto">
          <div className="w-12 h-12 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 flex items-center justify-center mx-auto">
            <Sparkles className="w-6 h-6" />
          </div>
          <div className="space-y-1">
            <h3 className="text-lg font-semibold text-white">Generate Job-Specific Cover Letter</h3>
            <p className="text-xs text-neutral-400 leading-relaxed">
              Click below to trigger AG-005. The agent will craft a personalized cover letter for "{selectedJob.title}" at "{selectedJob.company}" using your DATA-004 resume version.
            </p>
          </div>
          <Button
            variant="whitePill"
            onClick={handleGenerate}
            isLoading={isLoading}
            rightIcon={<Sparkles className="w-4 h-4 text-black" />}
          >
            {isLoading ? 'Generating custom cover letter...' : 'Generate Cover Letter (AG-005)'}
          </Button>
        </Card>
      )}

      {/* COVER LETTER EDIT & REVIEW DOCUMENT PREVIEW */}
      {coverLetter && (
        <div className="space-y-6 max-w-3xl mx-auto">
          <div className="p-8 bg-white text-slate-900 border border-slate-300 rounded-2xl shadow-2xl space-y-6 select-text">
            <div className="border-b border-slate-200 pb-4 flex justify-between items-start">
              <div>
                <h2 className="text-xl font-bold text-slate-900">
                  Cover Letter for {selectedJob.title}
                </h2>
                <p className="text-xs text-slate-500 mt-0.5">
                  Company: <span className="font-semibold text-slate-800">{selectedJob.company}</span>
                </p>
              </div>
              <Badge variant="dark" size="sm">DATA-010 Persisted</Badge>
            </div>

            {/* Editable Cover Letter Body */}
            <div className="space-y-2">
              <label className="text-[11px] font-semibold uppercase tracking-wider text-slate-500 block">
                User Review & Editing Area
              </label>
              <textarea
                value={editableContent}
                onChange={e => setEditableContent(e.target.value)}
                rows={16}
                className="w-full p-4 rounded-xl border border-slate-200 text-xs leading-relaxed font-sans text-slate-800 focus:outline-none focus:ring-2 focus:ring-slate-400 bg-white"
              />
            </div>

            {/* Action Toolbar */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pt-4 border-t border-slate-200 text-xs">
              <div className="flex items-center gap-2">
                <Button
                  variant="whitePill"
                  size="sm"
                  onClick={handleSaveEdits}
                  leftIcon={<Save className="w-3.5 h-3.5" />}
                >
                  Save Edits
                </Button>
                {saveSuccess && (
                  <span className="text-emerald-600 font-semibold flex items-center gap-1">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600" /> Saved!
                  </span>
                )}
              </div>

              <Button
                variant="ghost"
                size="sm"
                className="text-slate-700 hover:text-slate-900"
                onClick={handleGenerate}
                isLoading={isLoading}
                leftIcon={<RefreshCw className="w-3.5 h-3.5" />}
              >
                Regenerate Draft
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
